// Generated by CoffeeScript 1.3.3
(function() {
  var logic_hooks, schemas, _;

  schemas = require('./schemas');

  logic_hooks = require("./modules/Notifications/logic_hook");

  _ = require("underscore");

  module.exports = function(app, mongoose, io) {
    var NotificacionModel;
    NotificacionModel = mongoose.model('Notification', schemas.Notification);
    app.get('/api/notifications', function(req, res) {
      return NotificacionModel.find(function(err, notifications) {
        if (!err) {
          console.log(notifications);
          return res.send(notifications);
        } else {
          console.log(err);
          return res.send([]);
        }
      });
    });
    app.post('/api/notifications', function(req, res) {
      var notification;
      notification = null;
      console.log("POST: ");
      console.log(req.body);
      notification = new NotificacionModel({
        message: req.body.message,
        contact_id: req.body.contact_id,
        case_id: req.body.case_id
      });
      notification.save(function(err) {
        if (!err) {
          return console.log("created");
        } else {
          return console.log(err);
        }
      });
      _.map(logic_hooks.after_create, function(item) {
        try {
          console.log("api::notification::POST ", item.name);
          return item.callback(notification, io);
        } catch (e) {
          return console.log(e);
        }
      });
      return res.send(notification);
    });
    app.get('/api/notifications/:id', function(req, res) {
      return NotificacionModel.findById(req.params.id, function(err, notification) {
        if (!err) {
          return res.send(notification);
        } else {
          console.log(err);
          return {};
        }
      });
    });
    return app.put('/api/notifications/:id', function(req, res) {
      return NotificacionModel.findById(req.params.id, function(err, notification) {
        notification.status = req.body.status;
        return notification.save(function(err) {
          if (!err) {
            console.log("updated");
          } else {
            console.log(err);
          }
          return res.send(notification);
        });
      });
    });
  };

}).call(this);
